// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeleDanych.Data;

#nullable disable

namespace ModeleDanych.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424083434_WizytaChange")]
    partial class WizytaChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ModeleDanych.Models.Badanie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Badania");
                });

            modelBuilder.Entity("ModeleDanych.Models.DaneLogowania", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TypKonta")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("DaneLogowania");
                });

            modelBuilder.Entity("ModeleDanych.Models.Dostawa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDostawy")
                        .HasColumnType("TEXT");

                    b.Property<int>("MagazynId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZamowienieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("MagazynId");

                    b.HasIndex("ZamowienieId");

                    b.ToTable("Dostawy");
                });

            modelBuilder.Entity("ModeleDanych.Models.Gabinet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SzpitalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SzpitalId");

                    b.ToTable("Gabinet");
                });

            modelBuilder.Entity("ModeleDanych.Models.Grafik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataKoniec")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("GabinetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PracownikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("GabinetId");

                    b.HasIndex("PracownikId");

                    b.ToTable("Grafik");
                });

            modelBuilder.Entity("ModeleDanych.Models.Lekarz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPracownika")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specjalizacja")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("IdPracownika")
                        .IsUnique();

                    b.ToTable("Lekarz");
                });

            modelBuilder.Entity("ModeleDanych.Models.Magazyn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SzpitalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SzpitalId")
                        .IsUnique();

                    b.ToTable("Magazyn");
                });

            modelBuilder.Entity("ModeleDanych.Models.Pacjent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("DaneLogowaniaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NrTel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DaneLogowaniaId")
                        .IsUnique();

                    b.ToTable("Pacjent");
                });

            modelBuilder.Entity("ModeleDanych.Models.Poradnia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SzpitalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SzpitalId");

                    b.ToTable("Poradnia");
                });

            modelBuilder.Entity("ModeleDanych.Models.Pracownik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("DaneLogowaniaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NrTel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stanowisko")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SzpitalId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Wyplata")
                        .HasColumnType("REAL")
                        .HasColumnName("Wypłata");

                    b.HasKey("ID");

                    b.HasIndex("DaneLogowaniaId")
                        .IsUnique();

                    b.HasIndex("SzpitalId");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("ModeleDanych.Models.Procedura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataWykonania")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoDodatkowe")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LekarzWykonujacyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacjentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkierowanieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypBadaniaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("LekarzWykonujacyId");

                    b.HasIndex("PacjentId");

                    b.HasIndex("SkierowanieId")
                        .IsUnique();

                    b.HasIndex("TypBadaniaId");

                    b.ToTable("Procedury");
                });

            modelBuilder.Entity("ModeleDanych.Models.Produkt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Produkty");
                });

            modelBuilder.Entity("ModeleDanych.Models.Recepta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LekarzWystawiajacyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacjentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProduktId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("LekarzWystawiajacyId");

                    b.HasIndex("PacjentId");

                    b.HasIndex("ProduktId");

                    b.ToTable("Recepta");
                });

            modelBuilder.Entity("ModeleDanych.Models.Skierowanie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BadanieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LekarzWystawiajacyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacjentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("BadanieId");

                    b.HasIndex("LekarzWystawiajacyId");

                    b.HasIndex("PacjentId");

                    b.ToTable("Skierowania");
                });

            modelBuilder.Entity("ModeleDanych.Models.StanMagazynowy", b =>
                {
                    b.Property<int>("MagazynId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProduktId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ilosc")
                        .HasColumnType("INTEGER");

                    b.HasKey("MagazynId", "ProduktId");

                    b.HasIndex("ProduktId");

                    b.ToTable("StanMagazynowy");
                });

            modelBuilder.Entity("ModeleDanych.Models.Szpital", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Szpital");
                });

            modelBuilder.Entity("ModeleDanych.Models.Terminarz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProceduraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ProceduraId")
                        .IsUnique();

                    b.HasIndex("SalaId");

                    b.ToTable("Terminarz");
                });

            modelBuilder.Entity("ModeleDanych.Models.Wizyta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("GabinetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InformacjeDodatkowe")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LekarzId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PacjentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("GabinetId");

                    b.HasIndex("LekarzId");

                    b.HasIndex("PacjentId");

                    b.ToTable("Wizyty");
                });

            modelBuilder.Entity("ModeleDanych.Models.Wynik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpisBadania")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProceduraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ProceduraId")
                        .IsUnique();

                    b.ToTable("Wyniki");
                });

            modelBuilder.Entity("ModeleDanych.Models.Zamowienie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ilosc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProduktId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ProduktId");

                    b.ToTable("Zamowienia");
                });

            modelBuilder.Entity("ModeleDanych.Models.Dostawa", b =>
                {
                    b.HasOne("ModeleDanych.Models.Magazyn", "Magazyn")
                        .WithMany("Dostawy")
                        .HasForeignKey("MagazynId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Zamowienie", "Zamowienie")
                        .WithMany("Dostawy")
                        .HasForeignKey("ZamowienieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazyn");

                    b.Navigation("Zamowienie");
                });

            modelBuilder.Entity("ModeleDanych.Models.Gabinet", b =>
                {
                    b.HasOne("ModeleDanych.Models.Szpital", "Szpital")
                        .WithMany("Gabinety")
                        .HasForeignKey("SzpitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szpital");
                });

            modelBuilder.Entity("ModeleDanych.Models.Grafik", b =>
                {
                    b.HasOne("ModeleDanych.Models.Gabinet", "Gabinet")
                        .WithMany("Grafiki")
                        .HasForeignKey("GabinetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Pracownik", "Pracownik")
                        .WithMany("Grafiki")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gabinet");

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("ModeleDanych.Models.Lekarz", b =>
                {
                    b.HasOne("ModeleDanych.Models.Pracownik", "Pracownik")
                        .WithOne("Lekarz")
                        .HasForeignKey("ModeleDanych.Models.Lekarz", "IdPracownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("ModeleDanych.Models.Magazyn", b =>
                {
                    b.HasOne("ModeleDanych.Models.Szpital", "Szpital")
                        .WithOne("Magazyn")
                        .HasForeignKey("ModeleDanych.Models.Magazyn", "SzpitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szpital");
                });

            modelBuilder.Entity("ModeleDanych.Models.Pacjent", b =>
                {
                    b.HasOne("ModeleDanych.Models.DaneLogowania", "DaneLogowania")
                        .WithOne()
                        .HasForeignKey("ModeleDanych.Models.Pacjent", "DaneLogowaniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaneLogowania");
                });

            modelBuilder.Entity("ModeleDanych.Models.Poradnia", b =>
                {
                    b.HasOne("ModeleDanych.Models.Szpital", "Szpital")
                        .WithMany("Poradnie")
                        .HasForeignKey("SzpitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szpital");
                });

            modelBuilder.Entity("ModeleDanych.Models.Pracownik", b =>
                {
                    b.HasOne("ModeleDanych.Models.DaneLogowania", "DaneLogowania")
                        .WithOne()
                        .HasForeignKey("ModeleDanych.Models.Pracownik", "DaneLogowaniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Szpital", "Szpital")
                        .WithMany("Pracownicy")
                        .HasForeignKey("SzpitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaneLogowania");

                    b.Navigation("Szpital");
                });

            modelBuilder.Entity("ModeleDanych.Models.Procedura", b =>
                {
                    b.HasOne("ModeleDanych.Models.Lekarz", "LekarzWykonujacy")
                        .WithMany("WykonywaneProcedury")
                        .HasForeignKey("LekarzWykonujacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Pacjent", "Pacjent")
                        .WithMany("Procedury")
                        .HasForeignKey("PacjentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Skierowanie", "Skierowanie")
                        .WithOne("Procedura")
                        .HasForeignKey("ModeleDanych.Models.Procedura", "SkierowanieId");

                    b.HasOne("ModeleDanych.Models.Badanie", "TypBadania")
                        .WithMany("Procedury")
                        .HasForeignKey("TypBadaniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LekarzWykonujacy");

                    b.Navigation("Pacjent");

                    b.Navigation("Skierowanie");

                    b.Navigation("TypBadania");
                });

            modelBuilder.Entity("ModeleDanych.Models.Recepta", b =>
                {
                    b.HasOne("ModeleDanych.Models.Lekarz", "LekarzWystawiajacy")
                        .WithMany("Recepty")
                        .HasForeignKey("LekarzWystawiajacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Pacjent", "Pacjent")
                        .WithMany("Recepty")
                        .HasForeignKey("PacjentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Produkt", "Produkt")
                        .WithMany("Recepty")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LekarzWystawiajacy");

                    b.Navigation("Pacjent");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("ModeleDanych.Models.Skierowanie", b =>
                {
                    b.HasOne("ModeleDanych.Models.Badanie", "Badanie")
                        .WithMany("Skierowania")
                        .HasForeignKey("BadanieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Lekarz", "LekarzWystawiajacy")
                        .WithMany("Skierowania")
                        .HasForeignKey("LekarzWystawiajacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Pacjent", "Pacjent")
                        .WithMany("Skierowania")
                        .HasForeignKey("PacjentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badanie");

                    b.Navigation("LekarzWystawiajacy");

                    b.Navigation("Pacjent");
                });

            modelBuilder.Entity("ModeleDanych.Models.StanMagazynowy", b =>
                {
                    b.HasOne("ModeleDanych.Models.Magazyn", "Magazyn")
                        .WithMany("StanyMagazynowe")
                        .HasForeignKey("MagazynId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Produkt", "Produkt")
                        .WithMany("StanyMagazynowe")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazyn");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("ModeleDanych.Models.Terminarz", b =>
                {
                    b.HasOne("ModeleDanych.Models.Procedura", "Procedura")
                        .WithOne("Terminarz")
                        .HasForeignKey("ModeleDanych.Models.Terminarz", "ProceduraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Gabinet", "Sala")
                        .WithMany("Terminarze")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procedura");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ModeleDanych.Models.Wizyta", b =>
                {
                    b.HasOne("ModeleDanych.Models.Gabinet", "Gabinet")
                        .WithMany("Wizyty")
                        .HasForeignKey("GabinetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Lekarz", "Lekarz")
                        .WithMany("Wizyty")
                        .HasForeignKey("LekarzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModeleDanych.Models.Pacjent", "Pacjent")
                        .WithMany("Wizyty")
                        .HasForeignKey("PacjentId");

                    b.Navigation("Gabinet");

                    b.Navigation("Lekarz");

                    b.Navigation("Pacjent");
                });

            modelBuilder.Entity("ModeleDanych.Models.Wynik", b =>
                {
                    b.HasOne("ModeleDanych.Models.Procedura", "Procedura")
                        .WithOne("Wynik")
                        .HasForeignKey("ModeleDanych.Models.Wynik", "ProceduraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procedura");
                });

            modelBuilder.Entity("ModeleDanych.Models.Zamowienie", b =>
                {
                    b.HasOne("ModeleDanych.Models.Produkt", "Produkt")
                        .WithMany("Zamowienia")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("ModeleDanych.Models.Badanie", b =>
                {
                    b.Navigation("Procedury");

                    b.Navigation("Skierowania");
                });

            modelBuilder.Entity("ModeleDanych.Models.Gabinet", b =>
                {
                    b.Navigation("Grafiki");

                    b.Navigation("Terminarze");

                    b.Navigation("Wizyty");
                });

            modelBuilder.Entity("ModeleDanych.Models.Lekarz", b =>
                {
                    b.Navigation("Recepty");

                    b.Navigation("Skierowania");

                    b.Navigation("Wizyty");

                    b.Navigation("WykonywaneProcedury");
                });

            modelBuilder.Entity("ModeleDanych.Models.Magazyn", b =>
                {
                    b.Navigation("Dostawy");

                    b.Navigation("StanyMagazynowe");
                });

            modelBuilder.Entity("ModeleDanych.Models.Pacjent", b =>
                {
                    b.Navigation("Procedury");

                    b.Navigation("Recepty");

                    b.Navigation("Skierowania");

                    b.Navigation("Wizyty");
                });

            modelBuilder.Entity("ModeleDanych.Models.Pracownik", b =>
                {
                    b.Navigation("Grafiki");

                    b.Navigation("Lekarz");
                });

            modelBuilder.Entity("ModeleDanych.Models.Procedura", b =>
                {
                    b.Navigation("Terminarz");

                    b.Navigation("Wynik");
                });

            modelBuilder.Entity("ModeleDanych.Models.Produkt", b =>
                {
                    b.Navigation("Recepty");

                    b.Navigation("StanyMagazynowe");

                    b.Navigation("Zamowienia");
                });

            modelBuilder.Entity("ModeleDanych.Models.Skierowanie", b =>
                {
                    b.Navigation("Procedura");
                });

            modelBuilder.Entity("ModeleDanych.Models.Szpital", b =>
                {
                    b.Navigation("Gabinety");

                    b.Navigation("Magazyn");

                    b.Navigation("Poradnie");

                    b.Navigation("Pracownicy");
                });

            modelBuilder.Entity("ModeleDanych.Models.Zamowienie", b =>
                {
                    b.Navigation("Dostawy");
                });
#pragma warning restore 612, 618
        }
    }
}
